### ISSUE TITLE
missing value where TRUE/FALSE needed error

### ISSUE THREAD

**Issue by Diennguyen8290** [zhongguojie1998/CSOmap#2]
Hi,

Thanks for developing this tool.

I'm trying to reconstruct liver zonation using human healthy liver and running into the following error in  **coords <- optimization(affinityMat)** step:

Error in if (range > 50 && iter%%10 == 0) { : 
  missing value where TRUE/FALSE needed

The data can be found here: https://drive.google.com/drive/folders/1gsJ6AYIXzfa5G65ehBDzzJYFBvzOJZtU?usp=sharing 

Please could you help me have a look.

Thanks,
Dien

**Comment by zhongguojie1998** [comment]
Could you please attach the output log? It could be due to a large gradient.

**Comment by Pang-Ka** [comment]
I met the same problem when I run your demo data. To find the error reporting code, I run the CSOmap.R line by line and the error occurs when I run the following code:

```
#optimization
  coords <- optimization(affinityMat)

#Error in if (range > 50 && iter%%10 == 0) { : 
#missing value where TRUE/FALSE needed

```
Hope to get some help.
Thanks a lot.

**Comment by zhongguojie1998** [comment]
It should be good now, could you please try again?

**Comment by Pang-Ka** [comment]
It works now, thanks a lot!
