### ISSUE TITLE
questions about TPM transformation and labelsize

### ISSUE THREAD

**Issue by springwellflow** [zhongguojie1998/CSOmap#3]
Dear Zhong,
CSOmap is a good tool to investigate cell-cell conection and communication. I have meet some problems while analyzing  scRNA-seq 
 data with CSOmap and ask for your help.

1. How to transform the 10x genomics counts matrix to TPM matrix? Is this same as TPM transformation of RNA-seq counts to TPM? Like this:
eff_length <- abs(feature_info_full$end_position - feature_info_full$start_position)
feature_info_full <- cbind(feature_info_full,eff_length)
eff_length2 <- feature_info_full[,c(1,5)]
x <- expMatrix / eff_length2$eff_length
tpm = t( t(x) / colSums(x) ) * 1e6 

2. The demo data can run perfectly. However, I got a error report with my own data.  I am a green hand to matlab.  The cell numbers of some cell clusters in my data are below 50. Dose the error were caused by too small cell cluster size? How to fix the error?
{Error using parfor_endpoint_check (line 25)
The endpoint of a parfor range must be an integer. For more information see
Parallel Computing Toolbox, "parfor"

Error in analyst/getconnection (line 157)
            parfor i = 1 : labelsize

Error in analyst (line 66)
                obj = obj.getconnection(3);

Error in runme (line 33)
    a = analyst(outputpath, datapath, [outputpath, 'result/'], 1);

Error in csomap (line 2)
runme('liver')
} 

Thanks!

**Comment by zhongguojie1998** [comment]
You can transform 10x UMI counts to TPM by normalizing for each cell. The second issue is due to the cell cluster label, should not have space in the names.
