### ISSUE TITLE
how to get TPM from seurat

### ISSUE THREAD

**Issue by yuanG2000** [zhongguojie1998/CSOmap#5]
my data was saved in seurat object, i'd like to ask if there is an easy way to transform TPM from seurat count
thx a lot

**Comment by zhongguojie1998** [comment]
Hi, if your Seurat object is UMI counts then you can refer to https://satijalab.org/seurat/reference/normalizedata
and specify normalization.method = "RC"

**Comment by yuanG2000** [comment]
thanks for your reply,but i find normalization.method = "RC" for CPM caculation,it seems not for TPM

**Comment by zhongguojie1998** [comment]
CPM means counts per million, so if your data is UMI counts, then counts per million means transcripts per million, which is TPM.
If you data is not UMI counts (i.e. smart seq2). You may normalize the counts by gene lengths first, then normalize to million.

**Comment by yuanG2000** [comment]
got it!
my data is UMI counts,thx
